sudo: required

matrix:
  include:
    - python: 3.6
      language: python
      cache: pip
      install:
        - pip install codecov coverage
        - pip install -r requirements.txt
        - pip install -r requirements-dev.txt
      before_script:
        - export APP_CONFIG_FILE=$PWD/app/config/dev.py
        # remove encrypted file
        - rm app/config/prod.py
        - mv app/config/smtp.py.dist app/config/smtp.py
      script:
        - ./ci/lint.sh
        - coverage run setup.py test
      after_success:
        - codecov

    - language: nix
      script:
        - nix build --verbose
